name: "Swagger Detect Conflict and Update with Spring"
description: "Detects conflicts in the OpenAPI documentation and updates the Spring application"

inputs:
  path_openapi_docs:
    type: string
    required: true
    description: "Path to the OpenAPI documentation"
  module:
    type: string
    required: false
    description: "Module to build"
  github_token:
    type: string
    required: true
    description: "Github token"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      name: Checkout
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven

    # Selfcare-onboarding
    - uses: s4u/maven-settings-action@7802f6aec16c9098b4798ad1f1d8ac75198194bd # v3.0.0
      with:
        servers: '[{"id": "selfcare-onboarding", "username": "${{ github.actor }}", "password": "${{ inputs.github_token }}"}]'

    - name: Build with Maven
      run: |
        if [ -z "${{ inputs.module }}" ]; then
          mvn test -Dtest=SwaggerConfigTest#swaggerSpringPlugin -DfailIfNoTests=false
        else
          mvn test -pl :${{ inputs.module }}
        fi
      shell: bash

    - name: Install Optic
      run: npm install --location global @useoptic/optic
      shell: bash

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Download optic.yml
      run: curl https://raw.githubusercontent.com/pagopa/selfcare-commons/refs/heads/main/optic.yml -o optic.yml
      shell: bash

    - name: Check Open API by Optic
      id: optic_diff
      run: optic diff ${{ inputs.path_openapi_docs }} --base origin/${{ steps.extract_branch.outputs.branch }} --check
      shell: bash

    - name: Commit api-docs
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        if git diff --name-only HEAD | grep -q 'app/.*/api-docs'; then
          echo "Swagger documentation is older!!"
          exit 1
        fi
