name: 'Swagger Detect Conflict and Update with Spring'
description: 'Detects conflicts in the OpenAPI documentation and updates the Spring application'

inputs:
  path_openapi_docs:
    type: string
    required: true
    description: 'Path to the OpenAPI documentation'
  branch_ref:
    type: string
    required: true
    description: 'Branch reference to compare with'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      name: Checkout
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test -Dtest=SwaggerConfigTest#swaggerSpringPlugin -DfailIfNoTests=false
      shell: bash

    - name: Install Optic
      run: npm install --location global @useoptic/optic
      shell: bash

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check Open API by Optic
      id: optic_diff
      run: optic diff ${{ inputs.path_openapi_docs }} --base origin/${{ steps.extract_branch.outputs.branch }} --check
      shell: bash

    - name: Commit api-docs
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        git ls-files ./app** | grep 'api-docs*' 