name: 'Swagger Detect Conflict and Update with Spring'
description: 'Detects conflicts in the OpenAPI documentation and updates the Spring application'

inputs:
  path_openapi_docs:
    type: string
    required: true
  branch_ref:
    type: string
    required: true

env:
  HEAD_REF: ${{ github.head_ref }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ vars.HEAD_REF }}
        path: head
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Check out BASE revision
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: ${{ inputs.branch_ref }}
        path: base
    - name: Build with Maven
      working-directory: head
      run: mvn test -Dtest=SwaggerConfigTest#swaggerSpringPlugin -DfailIfNoTests=false
    - name: Run OpenAPI Diff (from HEAD revision)
      uses: mvegter/openapi-diff-action@72cde50f8d3a75f770f08e23b815d5ebe69ff757
      with:
        head-spec: head/${{ inputs.path_openapi_docs }}
        base-spec: base/${{ inputs.path_openapi_docs }}
    - name: Commit api-docs
      working-directory: head
      run: |
        git ls-files ./app** | grep 'api-docs*' | xargs git add .
        git config --global user.email "selfcare-github@pagopa.it"
        git config --global user.name "selfcare-github-bot"
        git commit -m "Update Swagger documentation" || exit 0
        git push origin ${{ vars.HEAD_REF }}