name: 'Swagger Detect Conflict and Update with Quarkus in monorepo'
description: 'Detects conflicts in the OpenAPI documentation and updates the Quarkus application'

inputs:
  path_openapi_docs:
    type: string
    required: true
    description: 'Path to the OpenAPI documentation'
  branch_ref:
    type: string
    required: true
    description: 'Branch reference to compare with'
  module:
    type: string
    required: true
    description: 'Module to build'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      name: Checkout
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn --projects :${{ inputs.module }} --also-make package -DskipTests
      shell: bash

    - name: Install Optic
      run: npm install --location global @useoptic/optic
      shell: bash

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check Open API by Optic
      id: optic_diff
      run: optic diff apps/${{ inputs.module }}/${{ inputs.path_openapi_docs }} --base ${{ steps.extract_branch.outputs.branch }}
      shell: bash

    - name: Commit api-docs
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        git ls-files ./apps/${{ inputs.module }}/** | grep 'openapi*' 