name: 'Swagger Detect Conflict and Update with Quarkus in monorepo'
description: 'Detects conflicts in the OpenAPI documentation and updates the Quarkus application'

inputs:
  path_openapi_docs:
    type: string
    required: true
    description: 'Path to the OpenAPI documentation'
  module:
    type: string
    required: true
    description: 'Module to build'
  github_token:
    type: string
    required: true
    description: 'Github token'

runs:
  using: "composite"
  steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4 # v1.11.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: 'temurin'
        maven-version: '3.9.5'
        cache-enabled: true

    # Selfcare-onboarding
    - uses: s4u/maven-settings-action@7802f6aec16c9098b4798ad1f1d8ac75198194bd # v3.0.0
      with:
        servers: '[{"id": "selfcare-onboarding", "username": "${{ github.actor }}", "password": "${{ inputs.github_token }}"}]'
        
    - name: Build with Maven
      run: mvn --projects :${{ inputs.module }} --also-make package -DskipTests
      shell: bash

    - name: Install Optic
      run: npm install --location global @useoptic/optic
      shell: bash

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check Open API by Optic
      id: optic_diff
      run: optic diff apps/${{ inputs.module }}/${{ inputs.path_openapi_docs }} --base origin/${{ steps.extract_branch.outputs.branch }} --check
      shell: bash

    - name: Commit api-docs
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        git ls-files ./apps/${{ inputs.module }}/** | grep 'openapi*' | xargs git add
        git config --global user.email "selfcare-github@pagopa.it"
        git config --global user.name "selfcare-github-bot"
        git commit -m "chore: Update Swagger documentation" || exit 0
        git push origin $HEAD_REF