name: Deploy CDN

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: The environment to use
        type: string
      storage_account_name:
        required: true
        description: Storage account name
        type: string
      profile_name:
        required: true
        description: CDN profile name
        type: string
      endpoint_name:
        required: true
        description: CDN endpoint name
        type: string
      resource_group_name:
        required: true
        description: Resource group name
        type: string
      blob_container_name:
        required: true
        description: Blob container name
        type: string
      base_path:
        required: true
        description: Base path for cdn files
        type: string

env:
  BUNDLE_NAME: bundle
  ENV_FILE: ${{ inputs.environment }}.env
  ENV_SHORT: ${{ inputs.environment == 'dev' && 'd' || inputs.environment == 'uat' && 'u' || 'p' }}
  REACT_APP_ASSISTANCE_EMAIL: areariservata@assistenza.pagopa.it
  REACT_APP_OT_SRC: https://privacyportalde-cdn.onetrust.com/privacy-notice-scripts/otnotice-1.0.min.js
  REACT_APP_OT_TERMS_CONDITION_RESOURCE: https://privacyportalde-cdn.onetrust.com/77f17844-04c3-4969-a11d-462ee77acbe1/privacy-notices/6f92cced-3bd1-4859-9295-baecfc74c64a.json
  REACT_APP_OT_TOKEN: eyJjYWxsYmFja1VybCI6Imh0dHBzOi8vcHJpdmFjeXBvcnRhbC1kZS5vbmV0cnVzdC5jb20vcmVxdWVzdC92MS9wcml2YWN5Tm90aWNlcy9zdGF0cy92aWV3cyJ9
  REACT_APP_OT_TOS_RESOURCE: https://privacyportalde-cdn.onetrust.com/77f17844-04c3-4969-a11d-462ee77acbe1/privacy-notices/26403d01-dc46-4c89-be70-4894839cf639.json
  REACT_APP_ENABLE_ASSISTANCE: "true"
  REACT_APP_PAGOPA_HELP_EMAIL: "areariservata@assistenza.pagopa.it"

concurrency:
  group: ${{ github.workflow }}-cd
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check-out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version-file: ".node-version"
        cache: "yarn"
        cache-dependency-path: "yarn.lock"

    - name: Install dependencies
      run: yarn install --immutable
      working-directory: .

    - name: Build files
      env:
        INLINE_RUNTIME_CHUNK: 'false'
        REACT_APP_ENV: "${{ inputs.environment == 'prod' && 'PROD' || inputs.environment == 'uat' && 'UAT' || 'DEV' }}"
        REACT_APP_ENABLE_ASSISTANCE: "${{ env.REACT_APP_ENABLE_ASSISTANCE }}"
        REACT_APP_PAGOPA_HELP_EMAIL: "${{ env.REACT_APP_PAGOPA_HELP_EMAIL }}"
        REACT_APP_OT_SRC: "${{ env.REACT_APP_OT_SRC }}"
        REACT_APP_OT_TOKEN: "${{ env.REACT_APP_OT_TOKEN }}"
        REACT_APP_OT_TERMS_AND_CONDITION_RESOURCE: "${{ env.REACT_APP_OT_TERMS_CONDITION_RESOURCE }}"
        REACT_APP_OT_TOS_RESOURCE: "${{ env.REACT_APP_OT_TOS_RESOURCE }}"
      run: |
        # Loading environment variables from ${{ env.ENV_FILE }}
        export $(cat ./.github/workflows/env/${{ env.ENV_FILE }} | xargs)

        # Build
        yarn build
      shell: bash

    - name: Build info
      env:
        EXECUTION_ID: "${{ github.run_number }} - ${{ github.workflow }}(${{ github.run_id }})"
      run: printf "$EXECUTION_ID\n$(git name-rev --name-only FETCH_HEAD) $(git rev-parse HEAD)" > ${{ github.workspace }}/build/build.info
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: ${{ env.BUNDLE_NAME }}
        path: "${{ github.workspace }}/build"
        if-no-files-found: error
        retention-days: 7

    - name: Success
      id: success
      run: |
        echo "success=true" >> $GITHUB_OUTPUT

  deploy:
    needs:
      - build
    if: success()
    runs-on: 'ubuntu-22.04'
    environment: "${{ inputs.environment }}-cd"
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download Artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: ./${{ env.BUNDLE_NAME }}

      - name: Azure Login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: CDN Code Deploy
        run: |
          az storage blob sync -c '${{ env.BLOB_CONTAINER_NAME }}' --account-name ${{ env.STORAGE_ACCOUNT_NAME }} -s "./${{ env.BUNDLE_NAME }}" --destination '${{ env.BASE_PATH }}/'
          az cdn endpoint purge -g ${{ env.RESOURCE_GROUP }} -n ${{ env.ENDPOINT_NAME }} --profile-name ${{ env.CDN_PROFILE }} --content-paths "/${{ env.BASE_PATH }}" "/${{ env.BASE_PATH }}/*"
        env:
          BLOB_CONTAINER_NAME: ${{ inputs.blob_container_name }}
          STORAGE_ACCOUNT_NAME: "selc${{ env.ENV_SHORT }}${{ inputs.storage_account_name }}"
          CDN_PROFILE: selc-${{ env.ENV_SHORT }}-${{ inputs.profile_name}}
          ENDPOINT_NAME: selc-${{ env.ENV_SHORT }}-${{ inputs.endpoint_name }}
          RESOURCE_GROUP: selc-${{ env.ENV_SHORT }}-${{ inputs.resource_group_name }}
          BASE_PATH: ${{ inputs.base_path }}