on:
  workflow_call:

jobs:

  labeler:
    name: 'PR Labeler'
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write

    steps:

      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          sync-labels: true
